name: Compilar Nai Kernel e Recovery

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Baixar o código do repositório
      uses: actions/checkout@v4

    - name: Instalar compiladores e ferramentas
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-aarch64-linux-gnu make

    - name: Compilar o Sistema, Recovery e VBmeta
      run: |
        make

    - name: Estruturar arquivos de imagem (.img)
      run: |
        mv payload.bin nai-system.img
        mv payload_recovery.bin nai-recovery.img
        mv vbmeta.bin vbmeta.img

    - name: Disponibilizar Imagens para Download
      uses: actions/upload-artifact@v4
      with:
        name: Nai-OS-Images
        path: |
          nai-system.img
          nai-recovery.img
          vbmeta.img
          
