name: Compilar Nai Kernel e Recovery

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Baixar o código do repositório
      uses: actions/checkout@v4

    - name: Instalar compiladores e ferramentas
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-aarch64-linux-gnu make cpio

    - name: Compilar o Sistema, Recovery e VBmeta
      run: |
        make

    - name: Estruturar Sysroot e Criar Imagem do Sistema
      run: |
        # 1. Cria a estrutura de pastas (incluindo os pontos de montagem vazios)
        mkdir -p sysroot/bin
        mkdir -p sysroot/dev
        mkdir -p sysroot/proc
        mkdir -p sysroot/sys
        mkdir -p sysroot/data

        # 2. Move o seu executável do setupwizard para o lugar correto
        mv payload.bin sysroot/bin/setupwizard

        # 3. Transforma a pasta sysroot em um ramdisk cpio (nai-system.img)
        cd sysroot
        find . -print0 | cpio --null -ov --format=newc > ../nai-system.img
        cd ..

    - name: Estruturar arquivos de imagem restantes
      run: |
        mv payload_recovery.bin nai-recovery.img
        mv vbmeta.bin vbmeta.img

    - name: Disponibilizar Imagens para Download
      uses: actions/upload-artifact@v4
      with:
        name: Nai-OS-Images
        path: |
          nai-system.img
          nai-recovery.img
          vbmeta.img
          
